# Competition title, e.g. SoundCloud Remix Contest
title: Control Freak - Dirty Bomb Remix Contest

# Competition description
description: "Control Freak - Dirty Bomb Remix Contest. Up the filth & bomb the bass challenge"

# A link to your Terms, if needed. Leave blank, otherwise
terms: 

# URL to user on SoundCloud that will administer the remix app, e.g. http://soundcloud.com/leemartin
admin: http://soundcloud.com/control-freak

# URL to group on SoundCloud where remixes will be added, e.g. http://soundcloud.com/groups/soundcloud-remix
# You can start a new group here: http://soundcloud.com/groups/new
group: http://soundcloud.com/groups/control-freak-dirty-bomb-remix-contest

# These options customize certain aspects of the embedded SoundCloud players.
# You can view a full list of available parameters here: http://wiki.github.com/soundcloud/Widget-JS-API/widget-options
player_params: "&color=d7650b&text_buy_track=Vote For Remix&default_width =400"

# Facebook application that can administer pages generated by "Like" button.
# You can create a new Facebook app here: http://www.facebook.com/developers/createapp.php
# Then look for the "Application ID"
facebook_id:

# Size limit on remix upload size in Kilobytes
# Handy if you're deploying your app on Heroku which has an upload limit of 10MBs
upload_limit: 10000000

# Default parameters associated with all uploaded remixes
remix:
  
  # Remix description
  description: Control Freak - Dirty Bomb Remix Contest Entry
  
  # A space seperated list of tags
  tag_list: Control Freak Dirty Bomb Remix Contest
  
  # Should the remix be downloadable? true or false
  downloadable: false
  
  # License attributed to remix, if needed. Leave blank, otherwise
  # You can view a full list of licenses (use Value) here: http://wiki.github.com/soundcloud/api/11-licenses
  license: 