development:
  key: 057cb4072f7274c2a60cf381a0de8266
  secret: 4a381ce3511bc8e92dc8e12a3f2ab8f7
  # base_url: "http://api.sandbox-soundcloud.com"
  base_url: "http://api.soundcloud.com"
  remember_for: 0 # do not change
  oauth_callback: "http://soundcloud-remix.dev/oauth_callback"
test:
  key: ddf38356604adc5b047a36477c2c5ff5
  secret: ea857edc47e14f8e19e0190b6aa9c6f9
  base_url: "http://api.soundcloud.com"
  remember_for: 0 # do not change
  oauth_callback: "http://cf-remix.heroku.com/oauth_callback"
production:
  key: ddf38356604adc5b047a36477c2c5ff5
  secret: ea857edc47e14f8e19e0190b6aa9c6f9
  base_url: "http://api.soundcloud.com"
  remember_for: 0 # do not change
  oauth_callback: "http://cf-remix.heroku.com/oauth_callback"